# Copyright (c) 2024 Robert Cronin
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  
  start:
    cmds:
      - python -m app.main